<?php
// This script is to define the H1, the Aciton of the form.
// The html page will be generated by branches_add_modify_helper_admin.php.
$pageTitle = "Add A New Restaurant";
$pageDescription = "Add a new Restaurant in this page";
$pageAdmin = true;
$branchesH1 = "Add a new branch:";
$branchesAction = "branches_add_result.php";
include "branches_add_modify_helper_admin.php"; ?>