<?php
// This script is to define the H1, the Aciton of the form, and interaction with db.
// The html page will be generated by branches_add_modify_helper_admin.php.
$pageTitle = "Modify A Branch";
$pageDescription = "Modify a branch in this page";
$pageAdmin = true;
if (isset($_POST['submit'])) 
{
    $branchesH1 = "Modify a branch here:";
    $branchesAction = "branches_modify_result_admin.php";
    // todo run select sql here.
    include "branches_add_modify_helper_admin.php";
}
?>